### ISSUE TITLE
Registering event handlers

### ISSUE THREAD

**Issue by pauleveritt** [Jycraft/jycraft#1]
I see that mcapi.registerhook has the start of what appears to be event handlers. I'd like to try and accomplish what ScriptCraft has in:

https://github.com/walterhiggins/ScriptCraft/blob/master/docs/API-Reference.md#eventsplayermove

...which uses this hook:

https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/hook/player/PlayerMoveHook.html

...but it seems I'm a bit far off.

**Comment by Macuyiko** [comment]
This is indeed possible, see below:

![hooks](https://cloud.githubusercontent.com/assets/271897/8992701/50ed69da-3700-11e5-93be-44b7bbed3d12.png)

```
from mcapi import *
from net.canarymod.hook.player import PlayerMoveHook

def hookfunc(listener, hook):
  yell(str(hook.getPlayer().getName())+" is moving!")

registerhook(PlayerMoveHook, hookfunc)
```
