### ISSUE TITLE
Bundled HTTP server for static assets in editor

### ISSUE THREAD

**Issue by pauleveritt** [Jycraft/jycraft#10]
Based on https://github.com/Joris-van-der-Wel/WSHttpServer

Either run on a separate port or, if that class allows, extend the WebSocket http server to also serve static assets for non websocket requests.

**Comment by pauleveritt** [comment]
Daniel has a fork which does this, getting reviewed now.

**Comment by AngelMunoz** [comment]
I think this might be closed now, thoughts?

**Comment by pauleveritt** [comment]
> On Nov 27, 2015, at 2:51 PM, Angel Daniel Munoz Gonzalez notifications@github.com wrote:
> 
> I think this might be closed now, thoughts?
> 
> If you think you want to just use one port, you can leave it open. Otherwise, close it.

—Paul
