### ISSUE TITLE
print doesn't write to the console in Spigot

### ISSUE THREAD

**Issue by pauleveritt** [Jycraft/jycraft#16]
In the Canary version, stdout seems to be sent to the console. Doing print 'hello' thus spews something to the console.

What's the right way, in Python, to get something to appear on the console for Spigot?

**Comment by BenLewis-Seequent** [comment]
Now any output standard output/exceptions from the interpreter is now sent to the console as well as the client.

**Comment by pauleveritt** [comment]
Works, thanks.
