### ISSUE TITLE
Interpreter results sent over websocket one character at a time

### ISSUE THREAD

**Issue by pauleveritt** [Jycraft/jycraft#2]
When using the existing jycraft-web websocket client (and my Angular websocket client), if I send over something to be evaluated after login, the results get received one character at a time.

That is, if I do:

  print 'abcdef'

...in the ACE editor and console.debug the .onMessage handler, I see that each character in the string is a different onMessage event.

Here is, I believe, the relevant code snippet:

```
    final InteractiveInterpreter interpreter = connections.get(ws);
    boolean more = false;
    try {
        if (message.contains("\n")) {
            more = parse(interpreter, message, true);
        } else {
            buffers.put(ws, buffers.get(ws)+"\n"+message); 
            more = parse(interpreter, buffers.get(ws), false);
        }
    } catch (Exception e) {
        ws.send(e.toString()+"\n");
    }
    if (!more) buffers.put(ws, "");
    if (more) ws.send("... ");
    else ws.send(">>> ");
```

**Comment by Macuyiko** [comment]
Should now be improved thanks to buffering the outputstream in the interpreters, see commit c007350dc5f2532b023609a49aa8d17b2f2aedb3

**Comment by pauleveritt** [comment]
Great, thanks for working on this!

Is it ok if I file some tickets for a couple of other things, or should I wait and let you do what you have in mind?

—Paul

**Comment by Macuyiko** [comment]
Go for it, this is a good way for me to work on/keep track of things!
