### ISSUE TITLE
Use JSON over websocket

### ISSUE THREAD

**Issue by pauleveritt** [Jycraft/jycraft#3]
I'd like us to adopt a convention where the payload for messages, incoming and outgoing, is expected to be conformant JSON. I currently have to adopt a string parser to read parts of the responses, to determine how to dispatch.

The _semantics_ of the JSON is something we can discuss in a separate ticket. For example, a number of systems expect messages to be organized into "channels". We could do that in the payload, or we could later do that in the websocket URI. But that can be a different discussion.

**Comment by AngelMunoz** [comment]
since we have json over the websocket and we're discusing the semantics in another ticket I will close this
